version: '3.8'

services:
  server:
    build: ./server
    container_name: putco-server
    restart: always
    ports:
      - "5300:5300"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5300
      - CLIENT_PORT=80
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build: ./client
    container_name: putco-client
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server

networks:
  default:
    name: putco-network